/* 
 * I - TJ - engineered this DNA Factory to serve as the 
 * primary technical embodiment of Patent Claim 12 - Silicon 
 * DNA Anchor - This is the clinical engine that generates 
 * a bit-identical mathematical identity for any 
 * particulate mass entering the AIFS protocol
 * 
 * Mandate 01 - Agnostic Witnessing - I have designed this 
 * logic to be substrate-blind - It must produce the 
 * identical forensic witness regardless of the operating 
 * system (Windows - Posix - RTOS) or CPU architecture - 
 * Bit-equivalence is the only acceptable outcome
 * Mandate 02 - Universal Flexibility - The factory is 
 * agnostic to the nature of the data signal - It does 
 * not care if it is a transaction - a biometric signal - 
 * or a secure communication - It only sees the bits - 
 * This flexibility ensures that the AIFS protocol remains 
 * a universal technical standard
 * Mandate 03 - Concrete Anchoring - By replacing 'Abstract' 
 * metadata (filenames - headers) with a 'Concrete' 
 * mathematical DNA witness—I eliminate the risk of 
 * administrative falsification - The math is the only truth
 */

const crypto = require('crypto');

class DNAFactory {
    /**
     * I - TJ - mandated this function to generate the 
     * DNA Witness - I call this the Universal Thumbprint - 
     * It is derived through a sequential - deterministic 
     * hash of exactly 1,024 shards - This is Patent 
     * Claim 12 in physical form
     * 
     * Examiner Note - This process turns a disparate 
     * particulate mass into a single - concrete mathematical 
     * anchor - This anchor is what 'proves' the existence 
     * of the data without the system ever having to 'know' 
     * the content - This is the core of ZPK persistence
     */
    static generateWitness(shards) {
        // I use SHA256 because it is a globally recognized -
        // bit-perfect mathematical constant - I - TJ -
        // insist on sequential processing to ensure the
        // witness is mathematically tied to the specific
        // order of the 1,024 shards
        const hash = crypto.createHash('sha256');
        shards.forEach(shard => hash.update(shard));

        // PATENTS CLAIM 1: Global Uniqueness Guarantee
        hash.update(Date.now().toString());
        hash.update(crypto.randomBytes(16));

        // First 20 chars = SHA-256 hash of particle set (truncated)
        const hashPart = hash.digest('hex').toUpperCase().substring(0, 20);

        // Last 4 chars = HMAC-SHA256 engine signature (Easter egg)
        // Proves this anchor was generated by the AIFS ShatterEngine.
        // DNA_LOOKUP is a Render environment variable — never hardcoded.
        // Any anchor submitted without a valid signature is rejected at the API
        // layer before it ever reaches the Hook. Fabricated hex strings pass the
        // format check but fail here.
        const secret = process.env.DNA_LOOKUP;
        if (!secret) throw new Error('DNA_LOOKUP not configured. Cannot generate anchor.');
        const sig = crypto.createHmac('sha256', secret)
            .update(hashPart)
            .digest('hex')
            .toUpperCase()
            .substring(0, 4);

        const dna = hashPart + sig; // 24 chars total — format unchanged, Hook unaffected

        // ═══════════════════════════════════════════════════════════════════════
        // ██  PILOT BUILD-OUT BLOCK — DO NOT MODIFY WITHOUT READING THIS FULLY  ██
        // ═══════════════════════════════════════════════════════════════════════
        //
        // THE ANCHOR IS INTENTIONALLY LEFT AT 24 HEX CHARS (96 BITS) FOR THE
        // CONTROLLED DEMO ENVIRONMENT. THIS IS NOT ACCEPTABLE FOR PRODUCTION.
        //
        // WHY IT IS LEFT AS-IS:
        //   The Xahau Hook deployed on rHs7o2n6r6YaRkzhg7zZFa1VWwiEx84hKr
        //   (SetHook tx: 39249C41) validates the HookParameterValue format.
        //   Changing the anchor length here WITHOUT a simultaneous Hook update
        //   will cause every settlement transaction to be rolled back by the Hook.
        //   The Hook and this factory MUST be versioned and deployed together.
        //   The Hook lives on Xahau Mainnet and requires a specialist engineering
        //   firm to update. That engagement has not yet occurred.
        //
        // ── CHANGE 1: ANCHOR SIZE (REQUIRED FOR PRODUCTION) ──────────────────
        //
        //   Current:  24 hex chars = 96 bits of entropy (truncated SHA-256)
        //   Required: 64 hex chars = 256 bits (full SHA-256 output)
        //
        //   Why: 96 bits is below the forensic integrity threshold for a global
        //   financial compliance standard. At institutional transaction volumes,
        //   collision probability becomes non-negligible. The full 256-bit anchor
        //   is the correct standard for a ZPK protocol claiming forensic uniqueness.
        //
        //   Code change (one line):
        //     BEFORE: hash.digest('hex').toUpperCase().substring(0, 24)
        //     AFTER:  hash.digest('hex').toUpperCase()
        //
        //   Cascading changes required:
        //     - v1_api.js line ~794: regex /^[0-9A-F]{24}$/ → /^[0-9A-F]{64}$/
        //     - v1_api.js comments referencing "24-char anchor" and "48 hex chars"
        //       (HookParameterValue hex-encodes the anchor: 64 chars → 128 hex chars)
        //     - Hook WASM: update format validation and state_set buffer size
        //     - Hook WASM: update otxn_param read length accordingly
        //     - New SetHook transaction required on rHs7o2n6r6YaRkzhg7zZFa1VWwiEx84hKr
        //
        // ── CHANGE 2: ENGINE SIGNATURE / EASTER EGG — ✅ LIVE AT API LAYER ─────
        //
        //   Status:   IMPLEMENTED April 2026. The last 4 chars of every anchor are
        //             an HMAC-SHA256 signature derived from DNA_LOOKUP.
        //             verifyWitness() is called in v1_api.js before HookParameter
        //             injection. Fabricated anchors are rejected at the API layer.
        //
        //   What this closes:
        //     - Any actor submitting a hand-crafted anchor to the settle endpoint
        //       receives ZPK_ANCHOR_INVALID. Settlement never reaches the Hook.
        //     - Compliance-fraud vector closed for all traffic through AIFS API.
        //
        //   What is STILL REQUIRED for production (Hook-side verification):
        //     - Currently the Hook on Xahau cannot independently verify the engine
        //       signature. An actor who bypasses the AIFS API entirely and submits
        //       a transaction directly to Xahau with a fabricated HookParameter
        //       will still pass the Hook's format check.
        //     - Fix: Hook engineering firm must implement HMAC verification in the
        //       Hook WASM using the verification key installed as a HookParameter
        //       at SetHook time (DNA_LOOKUP never leaves Render/infra).
        //     - Until Hook-side verification is live, the engine signature provides
        //       API-layer enforcement only. Sufficient for the demo. Not sufficient
        //       for production with unknown institutional senders on public networks.
        //     - Upgrade path: Ed25519 signature replaces HMAC for production.
        //       Ed25519 is mathematically impossible to fabricate. HMAC can
        //       theoretically be brute-forced if the secret is ever compromised.
        //       Rotate DNA_LOOKUP on every pilot deployment as mitigation.
        //
        // ── CHANGE 3: INTEROPERABILITY ANCHOR PREFIX (REQUIRED FOR PRODUCTION) ─
        //
        //   The `DNA` prefix in the Memo field is currently convention, not enforced
        //   protocol. For multi-institution interoperability, the anchor format must
        //   be formally standardized:
        //
        //     Memo format:  DNA[64-char-hex][8-char-engine-sig]
        //     Total length: 3 + 64 + 8 = 75 chars in Memo
        //     HookParameter: name=444E41 ("DNA"), value=hex-encoded anchor (150 hex chars)
        //
        //   Any compliant ZPK implementation by any third party must produce an
        //   anchor in this exact format. The Hook verifies the format, the engine
        //   signature, and single-use state before accepting the transaction.
        //
        // ── DEPLOYMENT SEQUENCE FOR PILOT ────────────────────────────────────
        //
        //   Current demo state (v1 — April 2026):
        //     ✅ Engine signature embedded in anchor (API layer)
        //     ✅ verifyWitness() gate in settle route (API layer)
        //     ✅ Single-use replay protection via Hook state_set
        //     ✅ Format validation in Hook WASM
        //     ❌ Hook-side HMAC verification (requires engineering firm)
        //     ❌ Full 256-bit anchor (requires Hook update)
        //     ❌ Ed25519 upgrade (long-term production requirement)
        //
        //   Remaining changes MUST ship as a single coordinated release:
        //     1. This file (DNAFactory.js) — expand anchor to 64 chars (Change 1)
        //                                  — upgrade HMAC → Ed25519 (Change 2)
        //     2. v1_api.js — regex /^[0-9A-F]{24}$/ → /^[0-9A-F]{64}$/
        //     3. Hook WASM — format validation + HMAC/Ed25519 verification + buffer sizes
        //     4. New SetHook tx on rHs7o2n6r6YaRkzhg7zZFa1VWwiEx84hKr with
        //        updated Hook WASM hash and verification key as HookParameter
        //
        //   Do NOT deploy any one of these without the others.
        //
        // ═══════════════════════════════════════════════════════════════════════

        return dna;
    }

    /**
     * Verify that a DNA anchor was generated by the AIFS ShatterEngine.
     * Recomputes the HMAC signature from the hash portion and compares
     * it to the embedded signature in the last 4 chars of the anchor.
     * Returns false for any anchor that was not produced by this engine.
     */
    static verifyWitness(anchor) {
        if (!anchor || !/^[0-9A-F]{24}$/.test(anchor)) return false;
        const secret = process.env.DNA_LOOKUP;
        if (!secret) return false;
        const hashPart = anchor.substring(0, 20);
        const embeddedSig = anchor.substring(20, 24);
        const expectedSig = crypto.createHmac('sha256', secret)
            .update(hashPart)
            .digest('hex')
            .toUpperCase()
            .substring(0, 4);
        return embeddedSig === expectedSig;
    }
}

module.exports = DNAFactory;


